version: '3'

services:
  web:
    build: .
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8080"
    container_name: applifting_webapp
    volumes:
      - .:/applifting_webapp
    ports:
      - "8080:8080"
    depends_on: 
      - "db"

  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog
    ports: 
      - "5432:5432"

volumes:
  postgres_data: