version: '3'

services:
  web:
    build: .
    container_name: web
    volumes:
      - project:/applifting
      - static:/applifting/staticfiles
    ports:
      - "8080:8080"
    depends_on: 
      db:
        condition: service_healthy
      redis-server:
        condition: service_started
    environment:
      - HOST=db
      - PORT=5432

  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog
    ports: 
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-server:
    image: redis:6.0.8
    volumes:
      - redis_data:/data
    ports: 
      - "6379:6379"

volumes:
  postgres_data:
  project:
  redis_data:
  static:
