# Generated by Django 3.1 on 2020-09-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricestamp',
            options={'ordering': ['timestamp']},
        ),
    ]
