# Generated by Django 3.1 on 2020-09-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200926_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offers_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
