# Generated by Django 3.1 on 2020-09-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_offer_offers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offers_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
